version: "0.1"
services:
  service-center:
    image: servicecomb/service-center:latest
    container_name: sc
    ports:
      - 30100:30100

  kie:
    image: servicecomb/kie:latest
    container_name: kie
    environment:
      DB_KIND: embedded_etcd
    ports:
      - 30110:30110

  ux:
    image: servicecomb/ux:latest
    container_name: ux
    ports:
      - 4200:4200
    depends_on:
      service-center:
        condition: service_started
      kie:
        condition: service_started
